import type { AudioItem } from './types';

/**
 * List of available audio items with their metadata.
 */
export const AvailableAudioItems: AudioItem[] = [
  {
    id: 'AT-001',
    url: '/austria',
    name: 'austria',
    lat: 47.3681,
    lon: 13.7369,
    audioSrc: '/audio/Austria.mp3',
    json: '/data/austria.json',
    desc: 'Austria operates one of the most structured national warning systems in Europe, with 8,200+ sirens installed across the country. The modern framework was established in the 1950s and 1960s, when Cold War preparedness led to standardizing siren tones across the federal states. The current three-signal structure was codified in the Civil Protection Act (Katastrophenschutzgesetz) of 1980: a 3-minute steady tone for “Warning”, a 1-minute rising and falling tone for “Alarm”, and a 1-minute steady tone for “All-clear.” The rationale behind this structure was to ensure differentiation: the long steady warning tone indicates general preparedness, the wailing alarm indicates immediate danger (especially air raids or disasters), and the second steady tone provides psychological closure with an unambiguous “end of danger” message (Wikipedia Warning siren in Austria; BMI – Austrian Ministry of the Interior).\nSince 1998, Austria has held a nationwide annual siren test on the first Saturday of October, during which all three signals are sounded in sequence. This not only checks technical reliability but also reinforces public awareness. Authorities emphasize that when people hear the “Alarm” signal, they should immediately seek information via ORF (Austrian Broadcasting Corporation) or official channels. The clear temporal structure of the signals, combined with annual drills, reflects Austria’s goal of making alerts unmistakable while embedding them in civic culture as part of Cold War civil defense heritage adapted for modern disaster management (BMI – Katastrophenschutz; Wikipedia Warning siren in Austria).',
    sources: '',
  },
  {
    id: 'CZ-001',
    url: '/czechia',
    name: 'czechia',
    lat: 49.8175,
    lon: 15.473,
    audioSrc: '/audio/Czechia.mp3',
    json: '/data/czechia.json',
    desc: 'Czechia operates one of the most distinctive warning siren systems in Europe, a legacy of its Cold War civil defense infrastructure inherited from Czechoslovakia. The central and most important signal is the “Všeobecná výstraha” (General Warning), which takes the form of a 140-second rising and falling tone. This can be repeated up to three times with pauses of around three minutes between cycles. The unusually long duration was deliberately chosen to ensure that the alarm could be heard clear...\nAfter the dissolution of Czechoslovakia, the Czech Republic codified the use of these sirens in the Act on the Integrated Rescue System (2002), which preserved the Cold War pattern but broadened its scope to civilian emergencies. Today, the sirens are tested nationwide at 12:00 on the first Wednesday of every month, when the full 140-second wavering signal is broadcast so that the population can remain familiar with it. The accompanying instruction is always the same: people should go indoors, close win...',
    sources:
      'Ministry of the Interior of the Czech Republic, Civil Protection and Crisis Management: <a href="https://mvcr.cz" target="_blank">mvcr.cz – Civil Protection</a>',
    link: ['https://en.wikipedia.org/wiki/Civil_defense_siren#Czech_Republic'],
  },
  {
    id: 'DK-001',
    url: '/denmark',
    name: 'denmark',
    lat: 56.2639,
    lon: 9.5018,
    audioSrc: '/audio/Denmark.mp3',
    json: '/data/denmark.json',
    desc: 'Denmark’s modern siren system was introduced in 1993, replacing a patchwork of WWII-era alarms. The design was based on studies carried out by the Danish Emergency Management Agency (Beredskabsstyrelsen) in the late 1980s and early 1990s, which found that older tones were easily confused with fire brigade calls. To avoid confusion, the national standard settled on two core signals: a 45-second rising and falling tone (“Varsling” / Gå inden døre – Go indoors) and a 45-second steady tone (“Faren er forbi” – The danger is over). The intention was to provide a clear, recognizable acoustic pattern that would be both impossible to mistake for other uses of sirens and psychologically easy to distinguish between threat and all-clear (Beredskabsstyrelsen, siren information page; Wikipedia Warning siren in Denmark).\nThe system consists of about 1,000 electronic sirens distributed across Danish cities, covering roughly 80 % of the population. The sirens are centrally controlled by the national police and can also be triggered locally. Each year on the first Wednesday in May at 12:00, a full nationwide test is conducted: first the rising/falling “go indoors” warning, then after a pause, the steady “danger over” all-clear. This practice reinforces public familiarity and ensures technical reliability. Authorities emphasize that when people hear the rising/falling tone, they should immediately go indoors, close windows and doors, and seek information from DR (Danish Radio) or other official media channels (Beredskabsstyrelsen; Wikipedia Warning siren in Denmark).',
    sources:
      'Danish Emergency Management Agency (Beredskabsstyrelsen), official siren information: <a href="https://beredskabsstyrelsen.dk" target="_blank">beredskabsstyrelsen.dk</a> – Sirenerne',
    link: ['https://en.wikipedia.org/wiki/Warning_siren_in_Denmark'],
  },
  {
    id: 'FR-001',
    url: '/france',
    name: 'france',
    lat: 46.6034,
    lon: 1.8883,
    audioSrc: '/audio/France.mp3',
    json: '/data/france.json',
    desc: 'France’s Signal National d’Alerte (SNA) was introduced after the Second World War and standardized during the Cold War, when a nationwide acoustic warning system was considered essential for both air-raid defense and civil protection. The official pattern consists of three cycles of a rising and falling tone, each lasting one minute and 41 seconds, separated by five-second pauses. This format was designed to be long enough to ensure recognition while remaining distinct from other alarms, such as fire sirens. The Ministry of the Interior explains that the signal is intended to be clearly audible and mobilizing without being unnecessarily anxiety-inducing, a balance meant to capture attention without triggering panic.\nThe system is tested monthly on the first Wednesday at noon, with the full three-cycle alert followed by the all-clear, a steady 30-second tone. Officials describe the sound as recognizable thanks to its rising and falling character, underlining its intended clarity. Since 2022, the acoustic system has been complemented by FR-Alert, a cell broadcast service that delivers emergency notifications directly to mobile phones. Together, the Cold War–era sirens and modern digital alerts form the backbone of France’s contemporary civil protection strategy.',
    sources:
      'Sénat report, Signal National d’Alerte definition: <a href="https://senat.fr" target="_blank">senat.fr</a> – Rapport n° 595; Ministère de l’Intérieur, Historique de l’alerte: <a href="https://mobile.interieur.gouv.fr" target="_blank">mobile.interieur.gouv.fr</a> – Historique de l’alerte; – Comment réagir; FR-Alert official site: <a href="https://fr-alert.gouv.fr" target="_blank">fr-alert.gouv.fr</a>',
    link: ['https://en.wikipedia.org/wiki/Civil_defense_siren#France'],
  },
  {
    id: 'DE-001',
    url: '/germany',
    name: 'germany',
    lat: 51.1657,
    lon: 10.4515,
    audioSrc: '/audio/Germany.mp3',
    json: '/data/germany.json',
    desc: 'Germany’s siren signals trace their origins to Second World War air-raid alarms, where the Fliegeralarm was sounded with a two-minute wailing tone that was later standardized to one minute. In the 1950s, during the Cold War, the Federal Republic introduced a nationwide civil defense siren network, coordinated through local Warnämter (warning offices). The government adopted the Einheitssirene 1957 (E57) and other standardized models to create a dense network of about 80,000 sirens (Wikipedia, Warnung der Bevölkerung in der Bundesrepublik Deutschland). The tones were directly derived from wartime practice: the rising and falling “Heulton” (1 minute) as the warning signal and the steady tone (1 minute) as the all-clear. The rationale was that the wailing signal conveyed urgency and immediate danger, while the steady tone provided psychological closure and an unambiguous indication that the threat had passed (Wikipedia, Zivilschutzsignale; Hörmann Warnsysteme, <a href="https://hoermann-ws.de" target="_blank">hoermann-ws.de</a>).\nAfter the end of the Cold War, the centralized network was dismantled in the early 1990s, with roughly half of the sirens removed and responsibility devolved to municipalities (Hörmann Warnsysteme, <a href="https://hoermann-ws.de" target="_blank">hoermann-ws.de</a>). Today, there is no single binding national siren code, but since 2019 the Federal Office for Civil Protection and Disaster Assistance (BBK) recommends two basic signals: the 1-minute rising and falling tone for “Warning” and the 1-minute steady tone for “All-clear” (Wikipedia, Warnung der Bevölkerung in der Bundesrepublik Deutschland). These remain rooted in the historical rationale of distinguishability and psychological clarity, ensuring that in emergencies the public immediately recognizes the acoustic cues and turns to radio, TV, or digital services such as MoWaS and Cell Broadcast for details.',
    sources:
      'Hörmann Warnsysteme (manufacturer, historical overview): <a href="https://hoermann-ws.de" target="_blank">hoermann-ws.de</a> – Warning systems in cities and municipalities',
    link: [
      'https://de.wikipedia.org/wiki/Warnung_der_Bevölkerung_in_der_Bundesrepublik_Deutschland',
    ],
  },
  {
    id: 'HU-001',
    url: '/hungary',
    name: 'hungary',
    lat: 47.1625,
    lon: 19.5033,
    audioSrc: '/audio/Hungary.mp3',
    json: '/data/hungary.json',
    desc: 'Hungary’s civil defense siren system has its roots in 1938, when the Minister of National Defense mandated the installation of warning sirens nationwide amid rising geopolitical tensions. Larger towns and cities received electric sirens—like the German-made FM Si 41, Swiss TESLA/Braun‐Boveri models, and domestically produced EKA and DINAMO types—while rural areas used hand-cranked versions and relied on radio broadcasts for alerts (Wikipedia, Civil defense siren – Hungary). Initially, t...\nBy 1944, the system expanded into a more graduated scheme:\n    • Air Warning—30 seconds of continuous siren when enemy forces were within 150 km;\n    • Red Alert—activated when an attack was expected within 15 minutes;\n    • Air Warning Over—signified attack subsidence;\n    • All-Clear—indicated full safety once threats moved beyond the 150 km threshold (Wikipedia, Civil defense siren – Hungary). After WWII, these systems were retained and, in the 1960s–1970s, replaced with standardized communist-era models like DDR DS977 and MEZ sirens under a major modernization effort. However, by the late 1990s, the centralized remote-control systems were deemed unreliable and dismantled as the perceived threat diminished (Wikipedia, Civil defense siren – Hungary).\nIn the mid-2000s, Hungary deployed MoLaRi—localized siren systems around hazardous material facilities—to provide targeted alerts for industrial emergencies. These systems remain active in certain counties and are tested monthly, typically the first Monday at 11:00, especially around Budapest where many hazard-prone facilities are located. A 2011 audit revealed many legacy sirens were nonfunctional; while some counties restored service, others did not, leaving a patchwork of operational readiness (Wikip...',
    sources:
      'Hungary Today, Monthly alarm tests & MoLaRi system: <a href="https://hungarytoday.hu/monthly-alarm-tests-siren-warnings-hungary-molari-system" target="_blank">hungarytoday.hu</a>',
    link: ['https://en.wikipedia.org/wiki/Civil_defense_siren#Hungary'],
  },
  {
    id: 'IS-001',
    url: '/island',
    name: 'island',
    lat: 64.9631,
    lon: -19.0208,
    audioSrc: '/audio/Island.mp3',
    json: '/data/island.json',
    desc: 'Iceland’s unique geological setting—marked by frequent volcanic activity, earthquakes, and extreme weather—has shaped its approach to public warning. Historically, mechanical sirens were the first form of early warning, particularly for potential military threats such as nuclear drills. In modern times, sirens are most often used for volcanic eruption warnings: for instance, in Grindavík and Svartsengi, loud, continuous evacuation sirens are activated when an eruption is imminent. Loca...\nAlongside sirens, Iceland relies heavily on mobile alerts and civil protection messaging. The Civil Protection Authority (Almannavarnir) and 112 emergency services use cell broadcasting via mobile networks to deliver alerts directly to phones in affected areas—no app download required—especially vital in reaching tourists and visitors. This system activates during eruptive or hazardous events, such as volcanic alerts or natural disasters, guiding people to evacuate or shelter as needed. The alerts are ...',
    sources:
      'Iceland Monitor, “Warning sirens in Grindavík and near the Blue Lagoon will be tested at 10 pm tonight” (Feb 2024 testing details); Visit Reykjanes, “Evacuation Sirens in Svartsengi and Grindavík” (Jul 2025 local siren function and test schedule); Almannavarnir (Icelandic Civil Protection), Emergency Response overview; EENA “Public Warning Systems: Lessons from Iceland” (mobile alert systems and cell broadcast use)',
  },
  {
    id: 'IT-001',
    url: '/italy',
    name: 'italy',
    lat: 41.8719,
    lon: 12.5674,
    audioSrc: '/audio/Italy.mp3',
    json: '/data/italy.json',
    desc: 'Italy’s civil defense siren system dates back to the late 1930s, when the Fascist government introduced mandatory air-raid warning infrastructure. In 1938, the War Ministry required that every city and town be equipped with at least one siren, with the production largely handled by La Sonora, a Milanese company specializing in electroacoustic devices (Italian Wikipedia, Unione nazionale protezione antiaerea). During World War II, two distinct alerts were used: the “piccolo allarme” (a preliminary signal about thirty minutes before expected air raids) and the “grande allarme” (signaling imminent danger). A steady signal indicated the end of the raid. These patterns were designed to give citizens clear advance warning and enough time to seek shelter (Italian Wikipedia, Unione nazionale protezione antiaerea; English Wikipedia, Civil defense siren – Italy).\nAfter the war, many of these sirens remained in service, often repurposed for civil protection and flood alerts, such as in Venice. In Rome, as of 2015, at least 34 wartime sirens were still installed, maintained, and occasionally tested (English Wikipedia, Civil defense siren – Italy). In recent years, Italy has shifted its focus to IT-Alert, a national cell broadcast system tested since 2019 and officially deployed in 2024. IT-Alert has already been used for real emergencies, including an explosion near Florence in December 2024, and during major events such as Pope Francis’s funeral in April 2025 (Italian Wikipedia, IT-Alert). While the acoustic sirens remain a legacy of wartime civil defense, IT-Alert represents Italy’s move toward digital mass communication, with the same goal of immediate, unmistakable warning for the public.',
    sources:
      '"Italian Wikipedia: Unione nazionale protezione antiaerea — <a href="https://it.wikipedia.org/wiki/Unione_nazionale_protezione_antiaerea" target="_blank">it.wikipedia.org/wiki/Unione_nazionale_protezione_antiaerea</a>',
    link: ['it.wikipedia.org/wiki/Unione_nazionale_protezione_antiaerea'],
  },
  {
    id: 'KW-001',
    url: '/kuwait',
    name: 'kuwait',
    lat: 29.3759,
    lon: 47.9774,
    audioSrc: '/audio/Kuwait.mp3',
    json: '/data/kuwait.json',
    desc: 'Kuwait’s civil defense relies on Federal Signal Modulator sirens—electronic speaker arrays—deployed nationwide following the retirement of older mechanical systems (like the Thunderbolt System 7000) in the late 20th century. These omnidirectional sirens emit a rising-and-falling alert tone lasting roughly three minutes, signaling immediate danger such as terrorism, flooding, severe storms, large fires, earthquakes, major chemical incidents, or nuclear emergencies. A complementary continuous tone of similar duration is used to indicate an all-clear. \nDuring a siren alert, the public is instructed to seek well-ventilated shelter, secure doors and windows, power down HVAC systems, tune into official government media, heed mobile app and broadcast alerts, follow authorities’ directions, assist neighbors, and avoid tying up emergency communication lines. The Ministry of Interior periodically conducts announced siren tests—for example, on November 5, 2024, at 10:00 a.m.—to verify system readiness and educate the public about signal meanings.',
    sources:
      'Wikipedia – <a href="https://en.wikipedia.org/wiki/Federal_Signal_Modulator">Federal Signal Modulator</a>; Kuwait MoI test announcement (KUNA/news agency); Civil Defense equipment history: <a href="https://en.wikipedia.org/wiki/Thunderbolt_(siren)">en.wikipedia.org/wiki/Thunderbolt_(siren)</a>',
    link: ['en.wikipedia.org/wiki/Civil_defense_siren;'],
  },
  {
    id: 'LU-001',
    url: '/luxembourg',
    name: 'luxembourg',
    lat: 49.8153,
    lon: 6.1296,
    audioSrc: '/audio/Luxembourg.mp3',
    json: '/data/luxembourg.json',
    desc: 'Luxembourg operates its national warning system through <a href="https://lu-alert.lu" target="_blank">LU-Alert</a>, which combines sirens with mobile notifications, broadcast media, and other official channels. The siren network is relatively small, with around a hundred devices distributed across municipalities, reflecting both the country’s Cold War civil defense heritage and its present-day emphasis on cross-border risks, particularly nuclear emergencies. This is a sample of the regular test tone. The other features are standardized into three signals: a pre-alarm, a one-minute modulated tone; a nuclear alarm, a modulated tone with interruptions repeated to emphasize urgency; and an end-of-alarm, a steady one-minute tone that functions as the all-clear.\n\nTo ensure both technical reliability and public recognition, Luxembourg tests the sirens on a monthly schedule, customarily the first Monday of each month, with the public informed that no protective action is required during the exercise. The Ministry of Home Affairs and Civil Protection emphasize that when the sirens are activated outside the test schedule, people should go indoors, stay tuned to radio or television, and consult <a href="https://lu-alert.lu" target="_blank">LU-Alert</a> for guidance. In this way, the familiar acoustic signals continue to serve as an audible reminder of the country’s civil defense history, even as they are integrated into a layered warning strategy that now relies increasingly on digital alerts. The coexistence of sirens and <a href="https://lu-alert.lu" target="_blank">LU-Alert</a> reflects a broader European pattern: Cold War–era infrastructures are maintained not as relics, but as redundant systems that reinforce public trust through recognition and repetition.',
    sources:
      'Luxembourg Government, Civil Protection press release on nationwide test: <a href="https://gouvernement.lu" target="_blank">gouvernement.lu</a>; RTL Today, Nationwide alert system test scheduled for Monday: <a href="https://today.rtl.lu" target="_blank">today.rtl.lu</a>',
    link: ['https://lu-alert.lu', 'LU-Alert'],
  },
  {
    id: 'NL-001',
    url: '/netherlands',
    name: 'netherlands',
    lat: 52.3676,
    lon: 4.9041,
    audioSrc: '/audio/Netherlands.mp3',
    json: '/data/netherlands.json',
    desc: 'The Netherlands’ network of about 4,000–4,200 public warning sirens has its roots in Cold War-era civil defense. To maintain public readiness and signal recognition, authorities began monthly nationwide tests of the system in 1952, but by 1993 this evolved into the current model: a test at 12:00 noon on the first Monday of each month, with the siren sounding continuously for 1 minute and 26 seconds. The rationale behind this specific length and frequency was twofold: to ensure techn...\nAs risks diversified—ranging from floods and chemical spills to terrorism—the Netherlands developed NL‑Alert, a Cell Broadcast system launched in the late 2000s, to provide contextual information via mobile phones. Unlike sirens, which only signal that \"something is happening,\" NL-Alert delivers a short message explaining the nature of the emergency and recommended actions. It’s designed to complement, not replace, the sirens—both for redundancy and public clarity (Everbridge case study on Dutch public ...',
    sources:
      'Stars and Stripes (2003): Resumption of monthly siren tests, rationale about public familiarity.; <a href="https://www.government.nl/" target="_blank">Government.nl</a>: Official details on monthly test timing (first Monday at 12:00, 1 min 26 s tone, emergency procedure).; DutchReview: Context on historical usage and modernization of the siren system.; Everbridge white paper (Ministry of Interior’s innovation): How NL-Alert augments sirens for message content.; Euronews: Examples of NL-Alert usage and integration.',
    link: ['https://www.government.nl/', ' Government.nl'],
  },
  {
    id: 'NO-001',
    url: '/norway',
    name: 'norway',
    lat: 60.472,
    lon: 8.4689,
    audioSrc: '/audio/Norway.mp3',
    json: '/data/norway.json',
    desc: 'Norway’s siren system has its origins in the Second World War, when German occupation forces installed air-raid sirens in major cities. After the war, these devices were integrated into a national civil defense framework during the 1950s, under the newly formed Directorate for Civil Protection (DSB). The signals were standardized into three main alerts: “Flyalarm” (Air raid alarm), consisting of short intermittent tones for about one minute; “Viktig melding – søk informasjon” (Important messag...\nToday, Norway’s sirens are maintained by the Directorate for Civil Protection and are tested twice annually, in January and June. The most emphasized signal is Viktig melding – søk informasjon, which instructs people to go indoors, close doors and windows, and tune into NRK P1 (public radio) or other official channels for further information. The clear behavioral cue embedded in the signal reflects Cold War thinking: sirens were never meant to convey details, only to command attention and direct citizens...',
    sources:
      'Norwegian Directorate for Civil Protection (DSB), siren system information: <a href="https://dsb.no" target="_blank">dsb.no</a> – Viktig melding på tyfon',
    link: ['https://en.wikipedia.org/wiki/Civil_defense_siren#Norway'],
  },
  {
    id: 'PL-001',
    url: '/poland',
    name: 'poland',
    lat: 51.9194,
    lon: 19.1451,
    audioSrc: '/audio/Poland.mp3',
    json: '/data/poland.json',
    desc: 'Poland’s warning siren signals were standardized during the 1960s, under Warsaw Pact civil defense doctrine, and remain largely unchanged today. The key patterns are a 3-minute modulated (rising and falling) tone for “General Alarm” and a 3-minute steady tone for “Alarm Cancellation/All-clear.” These signals were directly adapted from Soviet civil defense practice, where long-duration tones were intended to be unmistakable, to carry over noisy urban and industrial environments, and to be dis...\nAfter 1989, Poland modernized its civil protection framework but kept the same core acoustic signals, extending their use to cover not only military threats but also industrial accidents, floods, and other emergencies. The most recent 2025 regulation reaffirmed the use of the 3-minute modulated alarm and 3-minute steady cancellation signal as the national standard. Sirens remain under the authority of local governments but are coordinated by the national fire service and civil protection agencies. Their ...',
    sources:
      'ISAP (Internet System of Legal Acts, Poland), 2025 regulation on civil defense warning signals: <a href="https://isap.sejm.gov.pl" target="_blank">isap.sejm.gov.pl</a>',
    link: ['https://en.wikipedia.org/wiki/Civil_defense_siren#Poland'],
  },
  {
    id: 'SG-001',
    url: '/singapore',
    name: 'singapore',
    lat: 1.3521,
    lon: 103.8198,
    audioSrc: '/audio/Singapore.mp3',
    json: '/data/singapore.json',
    desc: 'Singapore’s Public Warning System (PWS), managed by the Singapore Civil Defence Force (SCDF), is a nationwide network of over 280 strategically placed Hörmann-designed sirens (ECN-based units) used to warn of imminent threats, including air raids and other emergencies. Historically, mechanical air-raid sirens were used during colonial times, but a modern electronic system was implemented in the early 1990s, with the first batch of 250 sirens installed by Hörmann in 1991 and tested in 1992. Today, these sirens are primarily deployed for public awareness and drills rather than actual threats.\nPWS sounds three main signals: the “Alarm” or attack tone—typically a rising and falling sound signaling imminent danger and prompting people to move immediately to shelters; the “All Clear” continuous tone indicating it’s safe to emerge; and the “Important Message” chime, used for broadcast alerts and widely heard during events like Total Defence Day (15 February) and Civil Defence Day (15 September). While the actual Alarm tone is seldom used, the Important Message signal is sounded annually, and the system is tested regularly, such as monthly at noon and during national commemorations. Upon hearing any PWS signal, the public is advised to tune to local radio or TV for official instructions and instructions from SCDF.',
    sources:
      'SCDF Public Warning System official page – <a href="https://www.scdf.gov.sg">scdf.gov.sg</a>; Wikipedia – Total Defence (Singapore)',
    link: ['https://en.wikipedia.org/wiki/Public_Warning_System_(Singapore)'],
  },
  {
    id: 'SI-001',
    url: '/slowenia',
    name: 'slowenia',
    lat: 46.1512,
    lon: 14.9955,
    audioSrc: '/audio/Slowenia.mp3',
    json: '/data/slowenia.json',
    desc: 'Slovenia maintains a nationwide siren system with around 1,560 operational units, mostly mounted on fire stations, municipal buildings, and public facilities. The network combines both older mechanical and modern electronic sirens, and it remains an important part of civil protection alongside newer digital tools. The signals are standardized into three main categories. The warning signal (Opozorilo na nevarnost) is a two-minute steady tone, used to indicate a general state of danger such as floo...\nIn addition to these general signals, Slovenia has developed special localized siren patterns for high-risk municipalities. For example, in Hrastnik and Trbovlje, where chlorine is handled in industrial facilities, a unique 100-second composite signal (30 seconds wailing, 40 seconds steady, 30 seconds wailing) warns of chlorine leaks. In river valleys such as Muta, Vuzenica, Podvelka, Radlje ob Dravi, Brežice, Krško, and Sevnica, a different 100-second signal consisting of alternating four-second bursts ...',
    sources:
      'Government of Slovenia, SI-ALERT system: <a href="https://www.gov.si/en/" target="_blank">gov.si – SI-ALERT public warning</a>; Total Slovenia News (2019), overview of siren tests and functions (<a href="https://totalslovenia-news.com" target="_blank">totalslovenia-news.com</a>).',
    link: ['https://en.wikipedia.org/wiki/Civil_defense_siren#Slovenia'],
  },
  {
    id: 'SE-001',
    url: '/sweden',
    name: 'sweden',
    lat: 60.1282,
    lon: 18.6435,
    audioSrc: '/audio/Sweden.mp3',
    json: '/data/sweden.json',
    desc: '"Sweden"s civil defense siren system has its origins in the Cold War era, when the government sought to establish a nationwide warning mechanism against potential air raids and other emergencies. The sirens were standardized to emit a one-minute rising and falling tone, known as the "Luftalarm" (air alarm), which was designed to be easily distinguishable from other sounds and to convey a sense of urgency (Swedish Civil Contingencies Agency, "Larm och varning," msb.se).\nDuring the Cold War, the sirens were integrated into a broader civil defense strategy that included public education campaigns on how to respond to air-raid warnings. The siren signal was intended to prompt citizens to seek shelter indoors and tune into local radio or television for further instructions (Swedish Civil Contingencies Agency, "Sirenvarning," msb.se).\nToday, Sweden continues to maintain its siren system, with regular monthly tests conducted on the first Monday at noon. The signal remains a one-minute rising and falling tone, followed by a one-minute steady tone indicating the all-clear. The Swedish government emphasizes that upon hearing the siren, citizens should go indoors and listen to official information channels for further instructions (Swedish Civil Contingencies Agency, "Larm och varning," msb.se). This approach reflects the Cold War-era rationale of ensuring clear communication and public safety through simple, recognizable signals.\nSources:\n    • Swedish Civil Contingencies Agency, Larm och varning: msb.se – Larm och varning\n    • Swedish Civil Contingencies Agency, Sirenvarning: msb.se – Sirenvarning',
    sources:
      '<a href="https://lagen.nu/" target="_blank">Civilförsvarskungörelse</a> (1960:377) statute text (riksdagen.se; lagen.nu); MSB VMA & outdoor warning pages incl. “Falsklarm” and signal specs <a href="https://msb.se/" target="_blank">(msb.se)</a>; Krisinformation VMA/Warning-systems pages <a href="https://krisinformation.se/" target="_blank">(krisinformation.se)</a>; MSB brochure “In case of crisis or war” <a href="https://rib.msb.se/" target="_blank">(rib.msb.se)</a>',
    link: ['forsvarsmakten.se', 'Hesa Fredrik'],
  },
  {
    id: 'CH-001',
    url: '/switzerland',
    name: 'switzerland',
    lat: 46.8182,
    lon: 8.2275,
    audioSrc: '/audio/Switzerland.mp3',
    json: '/data/switzerland.json',
    desc: 'Switzerland’s nationwide siren system dates back to 1936, when the first General Alarm was introduced for air-raid defense. During the postwar period and especially the Cold War, the Federal Office for Civil Protection (FOCP) expanded and standardized the network, linking sirens into a central control system. Two main signals were established: the General Alarm, a one-minute rising and falling tone repeated once after two minutes, and the Water Alarm, consisting of twelve low continuous tones of twenty seconds each, separated by ten-second pauses. The rationale for introducing the Water Alarm was Switzerland’s reliance on hydroelectric dams and the need to provide unmistakable warning of possible dam failures in Alpine regions, ensuring that the public could distinguish between a general emergency and a specific flood risk.\nSince the 1980s, Switzerland has conducted a nationwide annual siren test on the first Wednesday in February at 12 noon, involving both the General Alarm and the Water Alarm. The goal is twofold: to verify the technical reliability of the approximately 8,500 sirens (stationary and mobile) and to ensure the public maintains recognition of the distinctive signals. The FOCP emphasizes that both alarms are designed to trigger a clear behavioral response: upon hearing them, citizens are expected to go indoors and immediately tune in to radio or official information channels. This coupling of a distinctive acoustic pattern with mediated instructions reflects Cold War logic—making the signals simple, uniform, and unmistakable, while relying on media to deliver detailed guidance.',
    sources:
      'Alertswiss, Federal Office for Civil Protection (FOCP): <a href="https://alert.swiss/en/precaution/respond-correctly-when-in-danger.html" target="_blank">alert.swiss</a>',
    link: ['https://en.wikipedia.org/wiki/Civil_defense_siren#Switzerland'],
  },
  {
    id: 'US-001',
    url: '/usa',
    name: 'USA',
    lat: 37.0902,
    lon: -95.7129,
    audioSrc: '/audio/USA.mp3',
    json: '/data/usa.json',
    desc: 'In the United States, civil defense and outdoor warning sirens trace their roots to World War II, where systems were designed to warn the public of air raids or impending danger. Over time, the systems evolved to signal natural disasters such as tornadoes, flash floods, tsunamis, chemical spills, and earthquakes, with audible alerts adapted locally. Typically, the most common alert tone is a **steady, continuous signal lasting 3–5 minutes**, which indicates immediate danger like tornadoes or severe weather. Another tone—an undulating or wavering “attack” sound—may warn of military threats, tsunami, or other emergencies, depending on local jurisdictions. After hearing a siren, residents are advised to move indoors, tune into official sources like NOAA Weather Radio or local broadcast media, and follow instructions from authorities. While federal guidelines (such as FEMA’s CPG 1–17) exist, specifics—including the use and meaning of tones and the presence or absence of an “all clear” signal—can vary significantly between states, counties, and municipalities. Siren tests are commonly conducted on a **monthly or weekly** basis at set times to ensure functionality and familiarity with the alert system.',
    sources:
      'FEMA’s Outdoor Warning Systems Guide (CPG 1–17) – <a href="https://www.fema.gov" target="_blank">FEMA.gov</a>; NOAA / National Weather Service / local municipal sources – e.g. Ready Illinois, city of Wayne, IL siren FAQs',
    link: ['en.wikipedia.org/wiki/Civil_defense_siren'],
  },
];
