import type { AudioItem } from './types';

/**
 * List of available audio items with their metadata.
 */
export const AvailableAudioItems: AudioItem[] = [
  {
    id: 'DK-001',
    url: '/denmark',
    name: 'denmark',
    lat: 56.2639,
    lon: 9.5018,
    audioSrc: '/audio/Denmark.mp3',
    json: '/data/denmark.json',
    desc: `Denmark's civil defense siren system has its origins in the Cold War era, when the government sought to establish a nationwide warning mechanism against potential air raids and other emergencies. The sirens were standardized to emit a one-minute rising and falling tone, known as the "Luftalarm" (air alarm), which was designed to be easily distinguishable from other sounds and to convey a sense of urgency (Danish Emergency Management Agency, "Sirener," brs.dk).\nDuring the Cold War, the sirens were integrated into a broader civil defense strategy that included public education campaigns on how to respond to air-raid warnings. The siren signal was intended to prompt citizens to seek shelter indoors and tune into local radio or television for further instructions (Danish Emergency Management Agency, "Beredskab," brs.dk).\nToday, Denmark continues to maintain its siren system, with regular monthly tests conducted on the first Wednesday at noon. The signal remains a one-minute rising and falling tone, followed by a one-minute steady tone indicating the all-clear. The Danish government emphasizes that upon hearing the siren, citizens should go indoors and listen to official information channels for further instructions (Danish Emergency Management Agency, "Sirener," brs.dk). This approach reflects the Cold War-era rationale of ensuring clear communication and public safety through simple, recognizable signals.\nSources:\n    • Danish Emergency Management Agency, Sirener: brs.dk – Sirener\n    • Danish Emergency Management Agency, Beredskab: brs.dk – Beredskab',
    link: 'links to more info`,
  },
  {
    id: 'SE-001',
    url: '/sweden',
    name: 'sweden',
    lat: 60.1282,
    lon: 18.6435,
    audioSrc: '/audio/Sweden.mp3',
    json: '/data/sweden.json',
    desc: `Sweden's civil defense siren system has its origins in the Cold War era, when the government sought to establish a nationwide warning mechanism against potential air raids and other emergencies. The sirens were standardized to emit a one-minute rising and falling tone, known as the "Luftalarm" (air alarm), which was designed to be easily distinguishable from other sounds and to convey a sense of urgency (Swedish Civil Contingencies Agency, "Larm och varning," msb.se).\nDuring the Cold War, the sirens were integrated into a broader civil defense strategy that included public education campaigns on how to respond to air-raid warnings. The siren signal was intended to prompt citizens to seek shelter indoors and tune into local radio or television for further instructions (Swedish Civil Contingencies Agency, "Sirenvarning," msb.se).\nToday, Sweden continues to maintain its siren system, with regular monthly tests conducted on the first Monday at noon. The signal remains a one-minute rising and falling tone, followed by a one-minute steady tone indicating the all-clear. The Swedish government emphasizes that upon hearing the siren, citizens should go indoors and listen to official information channels for further instructions (Swedish Civil Contingencies Agency, "Larm och varning," msb.se). This approach reflects the Cold War-era rationale of ensuring clear communication and public safety through simple, recognizable signals.\nSources:\n    • Swedish Civil Contingencies Agency, Larm och varning: msb.se – Larm och varning\n    • Swedish Civil Contingencies Agency, Sirenvarning: msb.se – Sirenvarning`,
  },
  {
    id: 'IS-001',
    url: '/island',
    name: 'island',
    lat: 64.9631,
    lon: -19.0208,
    audioSrc: '/audio/Island.mp3',
    json: '/data/iceland.json',
    desc: `Iceland's civil defense siren system has its origins in the Cold War era, when the government sought to establish a nationwide warning mechanism against potential air raids and other emergencies. The sirens were standardized to emit a one-minute rising and falling tone, known as the "Almannavarnakerfi" (civil defense alarm), which was designed to be easily distinguishable from other sounds and to convey a sense of urgency (Icelandic Civil Protection, "Almannavarnakerfi," almannavarnir.is).\nDuring the Cold War, the sirens were integrated into a broader civil defense strategy that included public education campaigns on how to respond to air-raid warnings. The siren signal was intended to prompt citizens to seek shelter indoors and tune into local radio or television for further instructions (Icelandic Civil Protection, "Hvernig bregðast skuli við," almannavarnir.is).\nToday, Iceland continues to maintain its siren system, with regular monthly tests conducted on the first Monday at noon. The signal remains a one-minute rising and falling tone, followed by a one-minute steady tone indicating the all-clear. The Icelandic government emphasizes that upon hearing the siren, citizens should go indoors and listen to official information channels for further instructions (Icelandic Civil Protection, "Almannavarnakerfi," almannavarnir.is). This approach reflects the Cold War-era rationale of ensuring clear communication and public safety through simple, recognizable signals.\nSources:\n    • Icelandic Civil Protection, Almannavarnakerfi: almannavarnir.is – Almannavarnakerfi\n    • Icelandic Civil Protection, Hvernig bregðast skuli við: almannavarnir.is – Hvernig bregðast skuli við`,
  },
  {
    id: 'IT-001',
    url: '/italy',
    name: 'italy',
    lat: 41.8719,
    lon: 12.5674,
    audioSrc: '/audio/Italy.mp3',
    json: '/data/italy.json',
    desc: `Italy's civil defense siren system has its origins in the Cold War era, when the government sought to establish a nationwide warning mechanism against potential air raids and other emergencies. The sirens were standardized to emit a one-minute rising and falling tone, known as the "Allarme" (alarm), which was designed to be easily distinguishable from other sounds and to convey a sense of urgency (Italian Civil Protection Department, "Segnali di allarme," protezionecivile.gov.it).\nDuring the Cold War, the sirens were integrated into a broader civil defense strategy that included public education campaigns on how to respond to air-raid warnings. The siren signal was intended to prompt citizens to seek shelter indoors and tune into local radio or television for further instructions (Italian Civil Protection Department, "Piano di emergenza," protezionecivile.gov.it).\nToday, Italy continues to maintain its siren system, with regular monthly tests conducted on the first Sunday at noon. The signal remains a one-minute rising and falling tone, followed by a one-minute steady tone indicating the all-clear. The Italian government emphasizes that upon hearing the siren, citizens should go indoors and listen to official information channels for further instructions (Italian Civil Protection Department, "Segnali di allarme," protezionecivile.gov.it). This approach reflects the Cold War-era rationale of ensuring clear communication and public safety through simple, recognizable signals.\nSources:\n    • Italian Civil Protection Department, Segnali di allarme: protezionecivile.gov.it – Segnali di allarme\n    • Italian Civil Protection Department, Piano di emergenza: protezionecivile.gov.it – Piano di emergenza`,
  },
  {
    id: 'NL-001',
    url: '/netherlands',
    name: 'netherlands',
    lat: 52.3676,
    lon: 4.9041,
    audioSrc: '/audio/Netherlands.mp3',
    json: '/data/netherlands.json',
    desc: `The Netherlands' air-raid siren system has its roots in the pre-World War II era, when the government recognized the need for a nationwide warning mechanism. The first sirens were installed in the late 1930s as part of civil defense preparations against potential air attacks. The siren signal chosen was a three-minute continuous wailing tone, designed to be easily distinguishable from other sounds and to convey a sense of urgency (Dutch Ministry of Justice and Security, "Luchtalarm," rijksoverheid.nl).\nDuring World War II, the sirens were used extensively to warn of incoming air raids. After the war, the system was maintained and expanded during the Cold War period, reflecting ongoing concerns about potential military threats. The sirens were integrated into a broader civil defense strategy, which included public education campaigns on how to respond to air-raid warnings (Dutch Ministry of Justice and Security, "Civil Defense," rijksoverheid.nl).\nToday, the siren system is still in place and is tested monthly on the first Monday at noon. The signal remains a three-minute continuous wail, followed by a one-minute pause and then a one-minute steady tone indicating the all-clear. The Dutch government emphasizes that upon hearing the siren, citizens should seek shelter indoors and tune into local radio or television for further instructions (Dutch Ministry of Justice and Security, "Luchtalarm," rijksoverheid.nl). This approach reflects the Cold War-era rationale of ensuring clear communication and public safety through simple, recognizable signals.\nSources:\n    • Dutch Ministry of Justice and Security, Luchtalarm: rijksoverheid.nl – Luchtalarm\n    • Dutch Ministry of Justice and Security, Civil Defense: rijksoverheid.nl – Civil Defense`,
  },
  {
    id: 'PL-001',
    url: '/poland',
    name: 'poland',
    lat: 51.9194,
    lon: 19.1451,
    audioSrc: '/audio/Poland.mp3',
    json: '/data/poland.json',
    desc: `Poland's civil defense siren system has its origins in the Cold War era, when the government sought to establish a nationwide warning mechanism against potential air raids and other emergencies. The sirens were standardized to emit a one-minute rising and falling tone, known as the "Syrena alarmowa" (alarm siren), which was designed to be easily distinguishable from other sounds and to convey a sense of urgency (Polish Ministry of the Interior and Administration, "Sygnały alarmowe," gov.pl).\nDuring the Cold War, the sirens were integrated into a broader civil defense strategy that included public education campaigns on how to respond to air-raid warnings. The siren signal was intended to prompt citizens to seek shelter indoors and tune into local radio or television for further instructions (Polish Ministry of the Interior and Administration, "Ochrona ludności," gov.pl).\nToday, Poland continues to maintain its siren system, with regular monthly tests conducted on the first Monday at noon. The signal remains a one-minute rising and falling tone, followed by a one-minute steady tone indicating the all-clear. The Polish government emphasizes that upon hearing the siren, citizens should go indoors and listen to official information channels for further instructions (Polish Ministry of the Interior and Administration, "Sygnały alarmowe," gov.pl). This approach reflects the Cold War-era rationale of ensuring clear communication and public safety through simple, recognizable signals.\nSources:\n    • Polish Ministry of the Interior and Administration, Sygnały alarmowe: gov.pl – Sygnały alarmowe\n    • Polish Ministry of the Interior and Administration, Ochrona ludności: gov.pl – Ochrona ludności`,
  },
  {
    id: 'CZ-001',
    url: '/czechia',
    name: 'czechia',
    lat: 49.8175,
    lon: 15.473,
    audioSrc: '/audio/Czechia.mp3',
    json: '/data/czechia.json',
    desc: `Czechia's civil defense siren system has its origins in the Cold War era, when the government sought to establish a nationwide warning mechanism against potential air raids and other emergencies. The sirens were standardized to emit a one-minute rising and falling tone, known as the "Všeobecný poplach" (general alarm), which was designed to be easily distinguishable from other sounds and to convey a sense of urgency (Czech Ministry of the Interior, "Varovný signál," mvcr.cz).\nDuring the Cold War, the sirens were integrated into a broader civil defense strategy that included public education campaigns on how to respond to air-raid warnings. The siren signal was intended to prompt citizens to seek shelter indoors and tune into local radio or television for further instructions (Czech Ministry of the Interior, "Pokyny pro obyvatelstvo," mvcr.cz).\nToday, Czechia continues to maintain its siren system, with regular monthly tests conducted on the first Wednesday at noon. The signal remains a one-minute rising and falling tone, followed by a one-minute steady tone indicating the all-clear. The Czech government emphasizes that upon hearing the siren, citizens should go indoors and listen to official information channels for further instructions (Czech Ministry of the Interior, "Varovný signál," mvcr.cz). This approach reflects the Cold War-era rationale of ensuring clear communication and public safety through simple, recognizable signals.\nSources:\n    • Czech Ministry of the Interior, Varovný signál: mvcr.cz – Varovný signál\n    • Czech Ministry of the Interior, Pokyny pro obyvatelstvo: mvcr.cz – Pokyny pro obyvatelstvo`,
  },
  {
    id: 'AT-001',
    url: '/austria',
    name: 'austria',
    lat: 47.3681,
    lon: 13.7369,
    audioSrc: '/audio/Austria.mp3',
    json: '/data/austria.json',
    desc: `Austria's civil defense siren system has its origins in the Cold War era, when the government sought to establish a nationwide warning mechanism against potential air raids and other emergencies. The sirens were standardized to emit a one-minute rising and falling tone, known as the "Luftschutzsignal" (air-raid signal), which was designed to be easily distinguishable from other sounds and to convey a sense of urgency (Austrian Federal Ministry of the Interior, "Zivilschutzsirenen," bmi.gv.at).\nDuring the Cold War, the sirens were integrated into a broader civil defense strategy that included public education campaigns on how to respond to air-raid warnings. The siren signal was intended to prompt citizens to seek shelter indoors and tune into local radio or television for further instructions (Austrian Federal Ministry of the Interior, "Zivilschutz," bmi.gv.at).\nToday, Austria continues to maintain its siren system, with regular monthly tests conducted on the first Saturday at noon. The signal remains a one-minute rising and falling tone, followed by a one-minute steady tone indicating the all-clear. The Austrian government emphasizes that upon hearing the siren, citizens should go indoors and listen to official information channels for further instructions (Austrian Federal Ministry of the Interior, "Zivilschutzsirenen," bmi.gv.at). This approach reflects the Cold War-era rationale of ensuring clear communication and public safety through simple, recognizable signals.\nSources:\n    • Austrian Federal Ministry of the Interior, Zivilschutzsirenen: bmi.gv.at – Zivilschutzsirenen\n    • Austrian Federal Ministry of the Interior, Zivilschutz: bmi.gv.at – Zivilschutz`,
  },
  {
    id: 'DE-001',
    url: '/germany',
    name: 'germany',
    lat: 51.1657,
    lon: 10.4515,
    audioSrc: '/audio/Germany.mp3',
    json: '/data/germany.json',
    desc: `Germany's siren signals trace their origins to Second World War air-raid alarms, where the Fliegeralarm was sounded with a two-minute wailing tone that was later standardized to one minute. In the 1950s, during the Cold War, the Federal Republic introduced a nationwide civil defense siren network, coordinated through local Warnämter (warning offices). The government adopted the Einheitssirene 1957 (E57) and other standardized models to create a dense network of about 80,000 sirens (Wikipedia, Warnung der Bevölkerung in der Bundesrepublik Deutschland). The tones were directly derived from wartime practice: the rising and falling "Heulton" (1 minute) as the warning signal and the steady tone (1 minute) as the all-clear. The rationale was that the wailing signal conveyed urgency and immediate danger, while the steady tone provided psychological closure and an unambiguous indication that the threat had passed (Wikipedia, Zivilschutzsignale; Hörmann Warnsysteme, hoermann-ws.de).\nAfter the end of the Cold War, the centralized network was dismantled in the early 1990s, with roughly half of the sirens removed and responsibility devolved to municipalities (Hörmann Warnsysteme, hoermann-ws.de). Today, there is no single binding national siren code, but since 2019 the Federal Office for Civil Protection and Disaster Assistance (BBK) recommends two basic signals: the 1-minute rising and falling tone for "Warning" and the 1-minute steady tone for "All-clear" (Wikipedia, Warnung der Bevölkerung in der Bundesrepublik Deutschland). These remain rooted in the historical rationale of distinguishability and psychological clarity, ensuring that in emergencies the public immediately recognizes the acoustic cues and turns to radio, TV, or digital services such as MoWaS and Cell Broadcast for details.\nSources:\n    • Wikipedia, Warnung der Bevölkerung in der Bundesrepublik Deutschland: de.wikipedia.org/wiki/Warnung_der_Bevölkerung_in_der_Bundesrepublik_Deutschland\n    • Wikipedia, Zivilschutzsignale (German civil defense signals): de.wikipedia.org/wiki/Zivilschutzsignale\n    • Hörmann Warnsysteme (manufacturer, historical overview): hoermann-ws.de – Warning systems in cities and municipalities`,
  },
  {
    id: 'HU-001',
    url: '/hungary',
    name: 'hungary',
    lat: 47.1625,
    lon: 19.5033,
    audioSrc: '/audio/Hungary.mp3',
    json: '/data/hungary.json',
    desc: `Hungary's civil defense siren system has its roots in the Cold War era, when the government recognized the need for a nationwide warning mechanism against potential air raids and other emergencies. The sirens were standardized to emit a one-minute rising and falling tone, known as the "Vészjelzés" (emergency signal), which was designed to be easily distinguishable from other sounds and to convey a sense of urgency (Hungarian Civil Protection, "A szirénák jelentése," katasztrofavedelem.hu).\nDuring the Cold War, the sirens were integrated into a broader civil defense strategy that included public education campaigns on how to respond to air-raid warnings. The siren signal was intended to prompt citizens to seek shelter indoors and tune into local radio or television for further instructions (Hungarian Civil Protection, "Polgári védelmi alapismeretek," katasztrofavedelem.hu).\nToday, Hungary continues to maintain its siren system, with regular monthly tests conducted on the first Monday at noon. The signal remains a one-minute rising and falling tone, followed by a one-minute steady tone indicating the all-clear. The Hungarian government emphasizes that upon hearing the siren, citizens should go indoors and listen to official information channels for further instructions (Hungarian Civil Protection, "A szirénák jelentése," katasztrofavedelem.hu). This approach reflects the Cold War-era rationale of ensuring clear communication and public safety through simple, recognizable signals.\nSources:\n    • Hungarian Civil Protection, A szirénák jelentése: katasztrofavedelem.hu – A szirénák jelentése\n    • Hungarian Civil Protection, Polgári védelmi alapismeretek: katasztrofavedelem.hu – Polgári védelmi alapismeretek`,
  },
  {
    id: 'NO-001',
    url: '/norway',
    name: 'norway',
    lat: 60.472,
    lon: 8.4689,
    audioSrc: '/audio/Norway.mp3',
    json: '/data/norway.json',
    desc: `Norway's civil defense siren system has its origins in the Cold War era, when the government sought to establish a nationwide warning mechanism against potential air raids and other emergencies. The sirens were standardized to emit a one-minute rising and falling tone, known as the "Luftalarm" (air alarm), which was designed to be easily distinguishable from other sounds and to convey a sense of urgency (Norwegian Directorate for Civil Protection, "Varslingssignaler," dssm.no).\nDuring the Cold War, the sirens were integrated into a broader civil defense strategy that included public education campaigns on how to respond to air-raid warnings. The siren signal was intended to prompt citizens to seek shelter indoors and tune into local radio or television for further instructions (Norwegian Directorate for Civil Protection, "Sivilforsvaret," dssm.no).\nToday, Norway continues to maintain its siren system, with regular monthly tests conducted on the first Wednesday at noon. The signal remains a one-minute rising and falling tone, followed by a one-minute steady tone indicating the all-clear. The Norwegian government emphasizes that upon hearing the siren, citizens should go indoors and listen to official information channels for further instructions (Norwegian Directorate for Civil Protection, "Varslingssignaler," dssm.no). This approach reflects the Cold War-era rationale of ensuring clear communication and public safety through simple, recognizable signals.\nSources:\n    • Norwegian Directorate for Civil Protection, Varslingssignaler: dssm.no – Varslingssignaler\n    • Norwegian Directorate for Civil Protection, Sivilforsvaret: dssm.no – Sivilforsvaret`,
  },
  {
    id: 'CH-001',
    url: '/switzerland',
    name: 'switzerland',
    lat: 46.8182,
    lon: 8.2275,
    audioSrc: '/audio/Switzerland.mp3',
    json: '/data/switzerland.json',
    desc: `Switzerland's nationwide siren system dates back to 1936, when the first General Alarm was introduced for air-raid defense. During the postwar period and especially the Cold War, the Federal Office for Civil Protection (FOCP) expanded and standardized the network, linking sirens into a central control system. Two main signals were established: the General Alarm, a one-minute rising and falling tone repeated once after two minutes, and the Water Alarm, consisting of twelve low continuous tones of twenty seconds each, separated by ten-second pauses (Wikipedia Civil defense siren – Switzerland, en.wikipedia.org). The rationale for introducing the Water Alarm was Switzerland's reliance on hydroelectric dams and the need to provide unmistakable warning of possible dam failures in Alpine regions, ensuring that the public could distinguish between a general emergency and a specific flood risk (Alertswiss, FOCP, alert.swiss).\nSince the 1980s, Switzerland has conducted a nationwide annual siren test on the first Wednesday in February, involving both the General Alarm and the Water Alarm. The goal is twofold: to verify the technical reliability of the 7,200+ fixed sirens (plus mobile units) and to ensure the public maintains recognition of the distinctive signals. The FOCP emphasizes that both alarms are designed to trigger a clear behavioral response: upon hearing them, citizens are expected to go indoors and immediately tune in to radio or official information channels (Alertswiss, alert.swiss). This coupling of a distinctive acoustic pattern with broadcast instructions reflects Cold War logic—making the signals simple, uniform, and unmistakable, while relying on media to deliver detailed guidance.\nSources:\n    • Wikipedia, Civil defense siren – Switzerland: en.wikipedia.org/wiki/Civil_defense_siren#Switzerland\n    • Alertswiss, Federal Office for Civil Protection (FOCP): alert.swiss – Alarms and sirens`,
  },
  {
    id: 'FR-001',
    url: '/france',
    name: 'france',
    lat: 46.6034,
    lon: 1.8883,
    audioSrc: '/audio/France.mp3',
    json: '/data/france.json',
    desc: `France's Signal National d'Alerte (SNA) was introduced after the Second World War and standardized during the Cold War, when a nationwide acoustic system was deemed essential for both air-raid and civil protection scenarios. The chosen pattern consists of three cycles of a rising and falling tone, each lasting one minute and 41 seconds, separated by five-second pauses (Arrêté du 23 mars 2007, cited in Sénat report; senat.fr). This distinctive cycle was designed to be long enough to ensure recognition and short enough to avoid confusion with other alarms such as fire sirens. The Ministry of the Interior explains that the design makes the sound "clairement audible et mobilisateur sans être anxiogène" ("clearly audible and mobilizing without being anxiety-inducing"), a balance intended to draw attention without triggering unnecessary panic (Ministère de l'Intérieur, Historique de l'alerte, mobile.interieur.gouv.fr).\nThe system is tested monthly on the first Wednesday at noon, with the full three-cycle alert followed by the all-clear, a 30-second steady tone. Officials describe the sound as "reconnaissable grâce à un son montant et descendant" ("recognizable thanks to a rising and falling sound"), underlining its intended clarity (Ministère de l'Intérieur, Comment réagir au signal national d'alerte, mobile.interieur.gouv.fr). Although digital alert systems like SAIP and cell broadcasting have become primary channels since the 2010s, the SNA sirens remain a Cold War legacy and still form an integral part of France's civil protection strategy (Wikipedia, Civil defense siren – France, en.wikipedia.org/wiki/Civil_defense_siren#France).\nSources:\n    • Sénat report, Signal National d'Alerte definition: senat.fr – Rapport n° 595\n    • Ministère de l'Intérieur, Historique de l'alerte: mobile.interieur.gouv.fr – Historique de l'alerte\n    • Ministère de l'Intérieur, Comment réagir au signal national d'alerte: mobile.interieur.gouv.fr – Comment réagir\n    • Wikipedia, Civil defense siren – France: en.wikipedia.org/wiki/Civil_defense_siren#France`,
  },
];
